"use client";

import * as React from "react";
import { Settings, Eye, EyeOff, Loader2, BarChart3 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
} from "@/components/ui/card";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

interface AiSettingsClientProps {
  translations: {
    title: string;
    subtitle: string;
    apiKey: string;
    apiKeyPlaceholder: string;
    apiKeyDescription: string;
    showKey: string;
    hideKey: string;
    model: string;
    modelDescription: string;
    modelGpt35: string;
    modelGpt4: string;
    modelGpt4Turbo: string;
    maxTokens: string;
    maxTokensDescription: string;
    temperature: string;
    temperatureDescription: string;
    usageLimit: string;
    usageLimitDescription: string;
    autoGenerate: string;
    autoGenerateDescription: string;
    saveSuccess: string;
    saveError: string;
    usageStats: string;
    usageThisMonth: string;
    usagePercent: string;
    selectModel: string;
    save: string;
  };
}

interface SettingsForm {
  apiKey: string;
  model: string;
  maxTokens: number;
  temperature: number;
  usageLimit: number;
  autoGenerate: boolean;
}

export function AiSettingsClient({ translations: t }: AiSettingsClientProps) {
  const [settings, setSettings] = React.useState<SettingsForm>({
    apiKey: "",
    model: "",
    maxTokens: 2000,
    temperature: 0.7,
    usageLimit: 100,
    autoGenerate: false,
  });
  const [showApiKey, setShowApiKey] = React.useState(false);
  const [isSaving, setIsSaving] = React.useState(false);

  // Placeholder usage stats
  const usedThisMonth = 0;

  function handleChange<K extends keyof SettingsForm>(
    key: K,
    value: SettingsForm[K]
  ) {
    setSettings((prev) => ({ ...prev, [key]: value }));
  }

  async function handleSave() {
    setIsSaving(true);

    // Simulate API call
    await new Promise((resolve) => setTimeout(resolve, 1000));

    toast.success(t.saveSuccess);
    setIsSaving(false);
  }

  const usagePercent =
    settings.usageLimit > 0
      ? Math.round((usedThisMonth / settings.usageLimit) * 100)
      : 0;

  const models = [
    { value: "gpt-3.5-turbo", label: t.modelGpt35 },
    { value: "gpt-4", label: t.modelGpt4 },
    { value: "gpt-4-turbo", label: t.modelGpt4Turbo },
  ];

  return (
    <div className="space-y-6 max-w-3xl">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-bold tracking-tight flex items-center gap-2">
          <Settings className="h-6 w-6" />
          {t.title}
        </h1>
        <p className="text-sm text-muted-foreground">{t.subtitle}</p>
      </div>

      {/* Settings Form */}
      <Card>
        <CardHeader>
          <CardTitle>{t.title}</CardTitle>
          <CardDescription>{t.subtitle}</CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          {/* API Key */}
          <div className="space-y-2">
            <Label htmlFor="apiKey">{t.apiKey}</Label>
            <div className="flex gap-2">
              <div className="relative flex-1">
                <Input
                  id="apiKey"
                  type={showApiKey ? "text" : "password"}
                  value={settings.apiKey}
                  onChange={(e) => handleChange("apiKey", e.target.value)}
                  placeholder={t.apiKeyPlaceholder}
                  className="pr-20"
                />
                <Button
                  type="button"
                  variant="ghost"
                  size="sm"
                  className="absolute right-1 top-1/2 -translate-y-1/2 h-7 px-2"
                  onClick={() => setShowApiKey(!showApiKey)}
                >
                  {showApiKey ? (
                    <>
                      <EyeOff className="h-3.5 w-3.5 mr-1" />
                      {t.hideKey}
                    </>
                  ) : (
                    <>
                      <Eye className="h-3.5 w-3.5 mr-1" />
                      {t.showKey}
                    </>
                  )}
                </Button>
              </div>
            </div>
            <p className="text-xs text-muted-foreground">
              {t.apiKeyDescription}
            </p>
          </div>

          {/* Model */}
          <div className="space-y-2">
            <Label htmlFor="model">{t.model}</Label>
            <Select
              value={settings.model}
              onValueChange={(value) => handleChange("model", value)}
            >
              <SelectTrigger id="model">
                <SelectValue placeholder={t.selectModel} />
              </SelectTrigger>
              <SelectContent>
                {models.map((m) => (
                  <SelectItem key={m.value} value={m.value}>
                    {m.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            <p className="text-xs text-muted-foreground">
              {t.modelDescription}
            </p>
          </div>

          {/* Max Tokens */}
          <div className="space-y-2">
            <Label htmlFor="maxTokens">{t.maxTokens}</Label>
            <Input
              id="maxTokens"
              type="number"
              min={100}
              max={8000}
              step={100}
              value={settings.maxTokens}
              onChange={(e) =>
                handleChange("maxTokens", parseInt(e.target.value) || 2000)
              }
            />
            <p className="text-xs text-muted-foreground">
              {t.maxTokensDescription}
            </p>
          </div>

          {/* Temperature */}
          <div className="space-y-2">
            <Label htmlFor="temperature">
              {t.temperature}: {settings.temperature.toFixed(1)}
            </Label>
            <input
              id="temperature"
              type="range"
              min={0}
              max={1}
              step={0.1}
              value={settings.temperature}
              onChange={(e) =>
                handleChange("temperature", parseFloat(e.target.value))
              }
              className="w-full h-2 bg-muted rounded-lg appearance-none cursor-pointer accent-primary"
            />
            <div className="flex justify-between text-xs text-muted-foreground">
              <span>0</span>
              <span>0.5</span>
              <span>1</span>
            </div>
            <p className="text-xs text-muted-foreground">
              {t.temperatureDescription}
            </p>
          </div>

          {/* Usage Limit */}
          <div className="space-y-2">
            <Label htmlFor="usageLimit">{t.usageLimit}</Label>
            <Input
              id="usageLimit"
              type="number"
              min={1}
              max={10000}
              value={settings.usageLimit}
              onChange={(e) =>
                handleChange("usageLimit", parseInt(e.target.value) || 100)
              }
            />
            <p className="text-xs text-muted-foreground">
              {t.usageLimitDescription}
            </p>
          </div>

          {/* Auto Generate */}
          <div className="flex items-center justify-between rounded-lg border p-4">
            <div className="space-y-0.5">
              <Label htmlFor="autoGenerate" className="text-base">
                {t.autoGenerate}
              </Label>
              <p className="text-sm text-muted-foreground">
                {t.autoGenerateDescription}
              </p>
            </div>
            <Switch
              id="autoGenerate"
              checked={settings.autoGenerate}
              onCheckedChange={(checked) =>
                handleChange("autoGenerate", checked)
              }
            />
          </div>

          {/* Save Button */}
          <Button onClick={handleSave} disabled={isSaving} size="lg">
            {isSaving ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                {t.save}...
              </>
            ) : (
              t.save
            )}
          </Button>
        </CardContent>
      </Card>

      {/* Usage Statistics */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <BarChart3 className="h-5 w-5" />
            {t.usageStats}
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-3">
            <p className="text-sm">
              {t.usageThisMonth
                .replace("{used}", String(usedThisMonth))
                .replace("{limit}", String(settings.usageLimit))}
            </p>

            {/* Progress bar */}
            <div className="w-full bg-muted rounded-full h-3">
              <div
                className="bg-primary h-3 rounded-full transition-all"
                style={{ width: `${Math.min(usagePercent, 100)}%` }}
              />
            </div>

            <p className="text-xs text-muted-foreground">
              {t.usagePercent.replace("{percent}", String(usagePercent))}
            </p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
