import { getTranslations } from "next-intl/server";
import { AiSettingsClient } from "./ai-settings-client";

export default async function AiSettingsPage() {
  const t = await getTranslations("aiSettings");
  const tCommon = await getTranslations("common");

  return (
    <AiSettingsClient
      translations={{
        title: t("title"),
        subtitle: t("subtitle"),
        apiKey: t("apiKey"),
        apiKeyPlaceholder: t("apiKeyPlaceholder"),
        apiKeyDescription: t("apiKeyDescription"),
        showKey: t("showKey"),
        hideKey: t("hideKey"),
        model: t("model"),
        modelDescription: t("modelDescription"),
        modelGpt35: t("modelGpt35"),
        modelGpt4: t("modelGpt4"),
        modelGpt4Turbo: t("modelGpt4Turbo"),
        maxTokens: t("maxTokens"),
        maxTokensDescription: t("maxTokensDescription"),
        temperature: t("temperature"),
        temperatureDescription: t("temperatureDescription"),
        usageLimit: t("usageLimit"),
        usageLimitDescription: t("usageLimitDescription"),
        autoGenerate: t("autoGenerate"),
        autoGenerateDescription: t("autoGenerateDescription"),
        saveSuccess: t("saveSuccess"),
        saveError: t("saveError"),
        usageStats: t("usageStats"),
        usageThisMonth: t("usageThisMonth"),
        usagePercent: t("usagePercent"),
        selectModel: t("selectModel"),
        save: tCommon("save"),
      }}
    />
  );
}
